### PR TITLE
update apr calculation, remove bignumber.js

### PR DESCRIPTION
**Pull request by 0xchewbacca**

### CODE REVIEW

**Comment by 0xchewbacca** [comment]
Update APR calculation for xVader. There is no compound here, also remove bignumberjs since there is no exponent operator anymore.

**Review by yellowgh0st — APPROVED** [review]

**Comment by yellowgh0st** [comment]
Thanks very good.
Merged.

**Comment by 0xchewbacca** [comment]
@yellowgh0st i think it's not merged yet

**Comment by yellowgh0st** [comment]
It's merged. I have merged first into kovan environment and tested. Then merged kovan into other environments. Merge into main should be last since it's production to avoid quirks.

**Comment by 0xchewbacca** [comment]
ok got it

**Comment by yellowgh0st** [comment]
Might not be best, just works good to maintain different versions. We might optimize this flow later.

**Pull request closed without merging**
