### PR TITLE
Fix local dev env not (kick)starting properly 🚀

### PR DESCRIPTION
**Pull request by dimorphic**
Issues solved in this PR:

- [x] [env] Fix app not starting locally due to missing env key variables - add sample `.env` config for local dev
- [x] [defaults] Minor refactor

### CODE REVIEW

**Comment by dimorphic** [comment]
Note: preview link not working as i can't add/edit the env vars on the Vercel deployment. :<

**Comment by yellowgh0st** [comment]
Hey, thanks for PR but these changes are not needed.
You need to set up your local environment to get it working as you expect,
That is on purpose so we can have multiple environments running for tests and avoid committing secrets.
More chains might come later so only chain ID would need to be added into ternary condition (or more complex dynamic way). The Vercel deployments are provided with keys for certain branches.

The only thing which would help might be adding these vars into README.

**Review by yellowgh0st — COMMENTED** [review]
Redundant changes, we do that already.

**Comment by dimorphic** [comment]
@yellowgh0st : I know that you need to setup your env, that was the issue. You can't get up and running without debugging the error first with missing env vars. I added an `.env.sample` just so ppl can duplicate and get the app running fast in case they want to help fixing bugs.

Also the changes were taking into consideration other chains that might come in the future, hence the replace for the check on mainnet / testnet, so you can easy update in (one) place the chainID or make it more dynamic or whatever.

I also know that you added those vars to Vercel deployment env, but for local dev someone has to debug missing things. Also, agreed that the readme should be updated, was on my to-do list with other stuff.

Just my 2 cents.

**Comment by yellowgh0st** [comment]
Create another PR add only the sample and updated README.

**Comment by yellowgh0st** [comment]
The other changes are redundant. The chain ID already tells you what's the chain.

**Comment by dimorphic** [comment]
Roger.

**Pull request closed without merging**
