### PR TITLE
Responsive header

### PR DESCRIPTION
**Pull request by hankxstudio**
Screen Shot 2021-07-07 at 21 52 20

to fix #14

### CODE REVIEW

**Comment by yellowgh0st** [comment]
Why did use sass? It's not really needed.

**Comment by hankxstudio** [comment]
> Why did use sass? It's not really needed.

Hmm, just don't want to write styled component wrapper everywhere.

**Comment by yellowgh0st** [comment]
It is better becsuse it ensures thsy onky codd that is being applied is included.

**Comment by yellowgh0st** [comment]
Looks good, thanks!

**Pull request merged**
