### PR TITLE
Improve readme docs, fix local dev env & stake panels errors 🚀

### PR DESCRIPTION
**Pull request by dimorphic**
Issues solved in this PR:

- [x] [env] Fix app not starting locally due to missing env key variables - add sample `.env` config for local dev
- [x] [Readme] Add proper notes: short overview, requirements, get started steps, notes regarding 'env' config variables and community links
- [x] [Stake] Fix React render errors in `StakePanel` & `UnstakePanel` when showing a `Spinner` inside the `Text` node (invalid DOM nesting on div in p) #minor

### CODE REVIEW

**Comment by dimorphic** [comment]
@yellowgh0st : As requested.

Also, can we have that infographic image that's used here and in the Vader docs in some common repo (like: `vetherasset/branding`, maybe under a 'community' dir?) - so we can link it from there instead of the hard one from the Vader docs right now or even adding it to this repo as a file .. ? :/

**Comment by yellowgh0st** [comment]
Awesome

**Comment by yellowgh0st** [comment]
You've located the DOM nesting issue. I really enjoy that.

**Comment by yellowgh0st** [comment]
> @yellowgh0st : As requested.
> 
> Also, can we have that infographic image that's used here and in the Vader docs in some common repo (like: `vetherasset/branding`, maybe under a 'community' dir?) - so we can link it from there instead of the hard one from the Vader docs right now or even adding it to this repo as a file .. ? :/

Yes, this is a better approach. I agreed it can be collected in that location.

**Comment by dimorphic** [comment]
> > @yellowgh0st : As requested.
> > Also, can we have that infographic image that's used here and in the Vader docs in some common repo (like: `vetherasset/branding`, maybe under a 'community' dir?) - so we can link it from there instead of the hard one from the Vader docs right now or even adding it to this repo as a file .. ? :/
> 
> Yes, this is a better approach. I agree it can be collected in that location.

Naisu! 👍

**Review by yellowgh0st — APPROVED** [review]

**Pull request merged**
